# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abaefaf4c0a3d230862f736ae3cbb021a1bc69a7e949a6af4d73b3a60b37594fa21fb0a6259a023208e0c3c9527c68fc00ab21eeba3b90dc069e9bb5509a4cd0

test:
  secret_key_base: f7ac80169dbb8bf09e371dc3cb26178c0b0af4eaf26699ee7753049ec06686652077cbd12a30d0d83069494974ae9d874dcac99452eb346e36f725d4771e0c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
